### ISSUE TITLE
CI test failure

### ISSUE THREAD

**Issue by cjyar** [IronCoreLabs/recrypt-node-binding#101]
[This CI run](https://github.com/IronCoreLabs/recrypt-node-binding/runs/6962655002?check_suite_focus=true) failed. It only failed for our Mac builds.

>     dlopen(/Users/ironcore/actions-runner/_work/recrypt-node-binding/recrypt-node-binding/bin-package/index.node, 0x0001): tried: '/Users/ironcore/actions-runner/_work/recrypt-node-binding/recrypt-node-binding/bin-package/index.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/index.node' (no such file), '/usr/lib/index.node' (no such file)

**Comment by BobWall23** [comment]
Craig already fixed!
