### ISSUE TITLE
Node 21 support

### ISSUE THREAD

**Issue by ekampp** [IronCoreLabs/recrypt-node-binding#131]
Hey, I'd love to start using this and the associated wasm libraries but we have recently upgraded to Node 21, which you don't support yet.

Are there any plans to support Node 21? If so, when? 

Thanks in advance.

**Comment by skeet70** [comment]
The release for this is ready but is delayed by a [regression in Node 21](https://github.com/nodejs/node/issues/50989). That'll be fixed when either [Node 21.4.0](https://github.com/shelljs/shelljs/pull/1144) releases or [shelljs accepts this PR and releases](https://github.com/shelljs/shelljs/pull/1144).

This is reminding my of why we don't support non-LTS versions of Node :D.

**Comment by ekampp** [comment]
Thank you very much! 🤝 

I'm happy to upgrade to 22 if/when you drop 21.

**Comment by skeet70** [comment]
Support is out in the [github release](https://github.com/IronCoreLabs/recrypt-node-binding/releases/tag/0.10.1) and on [npm](https://www.npmjs.com/package/@ironcorelabs/recrypt-node-binding/v/0.10.1)
