### ISSUE TITLE
[SPIKE] Investigate possibility of using node-pre-gyp for our use case

### ISSUE THREAD

**Issue by ernieturner** [IronCoreLabs/recrypt-node-binding#3]
Figure out if we can use node-pre-gyp for the postinstall NPM step of pulling down the expected architecture binary from the expected location. We don't want node-pre-gyp to do anything with node-gyp, just the configuration/simplification of determining an architecture and pulling down the proper binary.

**Comment by clintfred** [comment]
Generated #7 #8 #9 #10 IronCoreLabs/iron-node#22
