### ISSUE TITLE
Support Mac M1

### ISSUE THREAD

**Issue by cjyar** [IronCoreLabs/recrypt-node-binding#99]
https://github.com/IronCoreLabs/recrypt-node-binding/runs/6751924442?check_suite_focus=true seems to indicate that we need to support arm64 on Mac:
>     dlopen(/Users/ironcore/actions-runner/_work/recrypt-node-binding/recrypt-node-binding/bin-package/index.node, 0x0001): tried: '/Users/ironcore/actions-runner/_work/recrypt-node-binding/recrypt-node-binding/bin-package/index.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/index.node' (no such file), '/usr/lib/index.node' (no such file)

**Comment by BobWall23** [comment]
Hopefully just add `arm64` to the build matrix.

**Comment by giarc3** [comment]
Should be fixed as part of https://github.com/IronCoreLabs/recrypt-node-binding/pull/100. The `setup-node` action takes an optional `architecture` parameter that we weren't passing, so it was defaulting to `x86_64` for all of them. I added `arch: arm64` to the necessary parts of our build matrix and used it for the `setup-node` action.
